import { create } from 'zustand';
import { Coach } from '../types';

interface CoachState {
  coaches: Coach[];
  selectedCoachId: string;
  setSelectedCoachId: (id: string) => void;
  toggleFavouriteCoach: (id: string) => void;
}

const mockCoaches: Coach[] = [
  {
    id: 'c-1',
    name: 'Karan Sharma',
    photo: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?auto=format&fit=crop&w=300&q=80',
    experience: '8 yrs exp',
    rating: 4.9,
    specialty: 'Strength & HIIT',
    yearsExperience: 8,
    specialization: 'Strength Training, Muscle Hypertrophy & High Intensity Cardio',
    languages: ['English', 'Hindi', 'Punjabi'],
    shortBio: 'Certified personal trainer with a passion for helping clients build long-term athletic strength and lean muscle from home.',
    price: 1200,
    verifiedBadge: true,
    certifications: ['ACE Certified Personal Trainer', 'ISSA Strength & Conditioning Specialist', 'CPR/AED Certified'],
    achievements: ['Trained 450+ clients across India', 'Featured in FitIndia Magazine 2025', 'Specialist Coach of the Year 2025 (VIRLA)'],
    reviews: [
      { reviewerName: 'Rahul V.', rating: 5, comment: 'Karan completely changed how I think about home workouts. High energy and great technique corrections!' },
      { reviewerName: 'Amit S.', rating: 4.8, comment: 'Punctual, professional, and very encouraging. Highly recommend him for strength training!' }
    ],
    workoutSpecialties: ['Strength Training', 'HIIT', 'Boxing', 'Mobility'],
    availability: ['07:00 AM - 08:00 AM', '08:00 AM - 09:00 AM', '09:00 AM - 10:00 AM', '05:00 PM - 06:00 PM', '07:00 PM - 08:00 PM'],
    level: 'Certified',
    completedSessions: 245,
    isFavourite: false,
  },
  {
    id: 'c-2',
    name: 'Priya Patel',
    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    experience: '6 yrs exp',
    rating: 4.8,
    specialty: 'Yoga & Pilates',
    yearsExperience: 6,
    specialization: 'Vinyasa Flow, Ashtanga Yoga, Core Rehabilitation & Pilates',
    languages: ['English', 'Gujarati', 'Hindi'],
    shortBio: 'Dedicated Yoga and Pilates teacher focusing on posture correction, core alignment, and stress reduction through breathwork.',
    price: 1100,
    verifiedBadge: true,
    certifications: ['RYT 500 Yoga Alliance Certified', 'Balanced Body Pilates Instructor', 'Pre-Natal & Post-Natal Yoga Specialist'],
    achievements: ['Conducted 600+ wellness hours', 'Co-founded MindfulFlow Retreats', 'Yoga Expert panelist for Wellness Weekly'],
    reviews: [
      { reviewerName: 'Sneha M.', rating: 5, comment: 'Priya has a wonderful calming presence. Her posture adjustments are incredibly helpful!' },
      { reviewerName: 'Deepa K.', rating: 4.6, comment: 'Perfect mix of strength and mindfulness. Loved the pregnancy guidance.' }
    ],
    workoutSpecialties: ['Yoga', 'Pilates', 'Stretching', 'Pregnancy Fitness'],
    availability: ['07:00 AM - 08:00 AM', '09:00 AM - 10:00 AM', '10:00 AM - 11:00 AM', '05:00 PM - 06:00 PM', '09:00 PM - 10:00 PM'],
    level: 'Certified',
    completedSessions: 190,
    isFavourite: true,
  },
  {
    id: 'c-3',
    name: 'Rohan Mehta',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    experience: '10 yrs exp',
    rating: 4.95,
    specialty: 'Boxing & Athletics',
    yearsExperience: 10,
    specialization: 'Boxing, Kickboxing, Functional Cardio & Speed-Agility training',
    languages: ['English', 'Hindi', 'Marathi'],
    shortBio: 'Former national level kickboxer offering dynamic boxing fitness and high-intensity agility workouts directly at your home.',
    price: 1500,
    verifiedBadge: true,
    certifications: ['WAKO Certified Kickboxing Coach', 'National Academy of Sports Medicine (NASM) CPT', 'FMS Level 1 Functional Movement Specialist'],
    achievements: ['National Kickboxing Bronze Medalist', 'Trainer to celebrity corporate executives', 'VIRLA Elite Master Trainer designation'],
    reviews: [
      { reviewerName: 'Vikram R.', rating: 5, comment: 'Rohan brings boxing gym energy to your living room. Brutal but incredibly satisfying workout!' },
      { reviewerName: 'Rohit J.', rating: 4.9, comment: 'Amazing pads drills. His attention to footwork and form is outstanding.' }
    ],
    workoutSpecialties: ['Boxing', 'HIIT', 'Strength Training', 'Mobility'],
    availability: ['07:00 AM - 08:00 AM', '08:00 AM - 09:00 AM', '05:00 PM - 06:00 PM', '07:00 PM - 08:00 PM', '09:00 PM - 10:00 PM'],
    level: 'Elite',
    completedSessions: 480,
    isFavourite: true,
  },
  {
    id: 'c-4',
    name: 'Anjali Rao',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=300&q=80',
    experience: '5 yrs exp',
    rating: 4.75,
    specialty: 'Dance & Stretching',
    yearsExperience: 5,
    specialization: 'Zumba Fitness, Dance Conditioning & Passive Decompression Stretching',
    languages: ['English', 'Kannada', 'Hindi'],
    shortBio: 'High-energy dance fitness instructor and passive stretching therapist specializing in active recovery and cardiovascular conditioning.',
    price: 1000,
    verifiedBadge: false,
    certifications: ['Licensed Zumba Instructor (L1 & L2)', 'AFAA Group Fitness Certification', 'Therapeutic Stretching Specialist'],
    achievements: ['Choreographed virtual wellness events for corporate giants', 'VIRLA Rising Star Coach award nominee', 'Certified 100+ seniors in active aging exercises'],
    reviews: [
      { reviewerName: 'Priyanka D.', rating: 4.8, comment: 'So much fun! The dance routines fly by, and I burn close to 400 calories every time.' },
      { reviewerName: 'Nisha G.', rating: 4.7, comment: 'Anjali is super positive. Her stretching session cured my chronic lower back stiffness.' }
    ],
    workoutSpecialties: ['Dance Fitness', 'Stretching', 'Senior Fitness', 'Mobility'],
    availability: ['07:00 AM - 08:00 AM', '09:00 AM - 10:00 AM', '04:00 PM - 05:00 PM', '05:00 PM - 06:00 PM', '07:00 PM - 08:00 PM'],
    level: 'Associate',
    completedSessions: 95,
    isFavourite: false,
  },
  {
    id: 'c-5',
    name: 'Vikram Gill',
    photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    experience: '7 yrs exp',
    rating: 4.85,
    specialty: 'Strength & Bodybuilding',
    yearsExperience: 7,
    specialization: 'Strength Training, Core Conditioning & Muscle Building',
    languages: ['English', 'Hindi', 'Punjabi'],
    shortBio: 'Expert coach dedicated to safe lifting and helping clients build solid muscle foundations with simple at-home equipment.',
    price: 1300,
    verifiedBadge: true,
    certifications: ['ISSA Personal Trainer Certified', 'FMS Level 2 Specialist'],
    achievements: ['Coached 200+ clients', 'Trainer Award 2024'],
    reviews: [],
    workoutSpecialties: ['Strength Training', 'Functional Training'],
    availability: ['07:00 AM - 11:00 AM', '04:00 PM - 08:00 PM'],
    level: 'Certified',
    completedSessions: 160,
    isFavourite: false,
  },
  {
    id: 'c-6',
    name: 'Sneha Deshmukh',
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    experience: '9 yrs exp',
    rating: 4.9,
    specialty: 'Pilates & Core Rehab',
    yearsExperience: 9,
    specialization: 'Classical Pilates, core rehab, spinal health',
    languages: ['English', 'Marathi', 'Hindi'],
    shortBio: 'Certified Pilates master focused on core stabilizer activation, posture repair, and back pain mitigation.',
    price: 1200,
    verifiedBadge: true,
    certifications: ['Balanced Body Pilates Certified', 'Rehab Trainer Specialist'],
    achievements: ['Pilates lead trainer for State Athletic Team'],
    reviews: [],
    workoutSpecialties: ['Pilates', 'Mobility & Stretching'],
    availability: ['08:00 AM - 12:00 PM', '03:00 PM - 07:00 PM'],
    level: 'Certified',
    completedSessions: 175,
    isFavourite: false,
  },
  {
    id: 'c-7',
    name: 'Arjun Nair',
    photo: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=300&q=80',
    experience: '12 yrs exp',
    rating: 4.98,
    specialty: 'Boxing & Elite Agility',
    yearsExperience: 12,
    specialization: 'Professional boxing coach, cardio padwork, HIIT conditioning',
    languages: ['English', 'Malayalam', 'Hindi'],
    shortBio: 'Former professional boxer bringing high-octane conditioning, reflexes, and pad-striking drills to your doorstep.',
    price: 1400,
    verifiedBadge: true,
    certifications: ['AIBA Certified Coach', 'NASM Performance Enhancement Specialist'],
    achievements: ['National Boxing Champion (2018)', 'Trained 10+ professional boxers'],
    reviews: [],
    workoutSpecialties: ['Boxing', 'Functional Training', 'HIIT'],
    availability: ['07:00 AM - 10:00 AM', '05:00 PM - 09:00 PM'],
    level: 'Elite',
    completedSessions: 395,
    isFavourite: false,
  },
  {
    id: 'c-8',
    name: 'Neha Sen',
    photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=300&q=80',
    experience: '8 yrs exp',
    rating: 4.8,
    specialty: 'Senior & Posture Care',
    yearsExperience: 8,
    specialization: 'Low-impact senior fitness, active aging, mobility posture care',
    languages: ['English', 'Bengali', 'Hindi'],
    shortBio: 'Caring fitness professional working to restore independence, balance, and joint strength in older adults.',
    price: 1100,
    verifiedBadge: true,
    certifications: ['ACE Senior Fitness Specialist', 'CPR & First Aid Lead'],
    achievements: ['Conducted 1000+ senior care home visits'],
    reviews: [],
    workoutSpecialties: ['Senior Fitness', 'Mobility & Stretching'],
    availability: ['09:00 AM - 01:00 PM', '02:00 PM - 06:00 PM'],
    level: 'Associate',
    completedSessions: 80,
    isFavourite: false,
  },
  {
    id: 'c-9',
    name: 'Rahul Varma',
    photo: 'https://images.unsplash.com/photo-1542206395-9feb3edaa68d?auto=format&fit=crop&w=300&q=80',
    experience: '6 yrs exp',
    rating: 4.7,
    specialty: 'Active Mobility & Rehab',
    yearsExperience: 6,
    specialization: 'Myofascial release, static and dynamic stretching, injury rehabilitation assistance',
    languages: ['English', 'Hindi', 'Telugu'],
    shortBio: 'Mobility coach specializing in helping desk-bound workers decompress and reverse joint stiffness.',
    price: 1000,
    verifiedBadge: false,
    certifications: ['FMS Certified Specialist', 'Active Release Techniques Certification'],
    achievements: ['Consultant for Corporate Posture Programs'],
    reviews: [],
    workoutSpecialties: ['Mobility & Stretching', 'Yoga'],
    availability: ['07:00 AM - 11:00 AM', '04:00 PM - 08:00 PM'],
    level: 'Associate',
    completedSessions: 75,
    isFavourite: false,
  },
  {
    id: 'c-10',
    name: 'Pooja Hegde',
    photo: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=300&q=80',
    experience: '7 yrs exp',
    rating: 4.82,
    specialty: 'Dance Fitness & Aerobics',
    yearsExperience: 7,
    specialization: 'High calorie dance cardio, group rhythm training, stamina',
    languages: ['English', 'Tulu', 'Hindi'],
    shortBio: 'Passionate dance coach who infuses beats, energy, and smiles into sweat-drenched home fitness sessions.',
    price: 1200,
    verifiedBadge: false,
    certifications: ['Zumba Pro Specialist', 'AFAA Aerobics Lead'],
    achievements: ['Choreographed national fitness campaigns'],
    reviews: [],
    workoutSpecialties: ['Dance Fitness', 'HIIT'],
    availability: ['08:00 AM - 10:00 AM', '05:00 PM - 08:00 PM'],
    level: 'Associate',
    completedSessions: 110,
    isFavourite: false,
  }
];

export const useCoachStore = create<CoachState>((set) => ({
  coaches: mockCoaches,
  selectedCoachId: '', // Default to empty (VIRLA chooses)
  setSelectedCoachId: (id) => set({ selectedCoachId: id }),
  toggleFavouriteCoach: (id) => set((state) => ({
    coaches: state.coaches.map(c => c.id === id ? { ...c, isFavourite: !c.isFavourite } : c)
  }))
}));
